# Generated by Django 5.1.1 on 2024-10-08 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointments",
            fields=[
                ("AppointmentID", models.AutoField(primary_key=True, serialize=False)),
                ("AppointmentDate", models.DateTimeField()),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Cancelled", "Cancelled"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Providers",
            fields=[
                ("ProviderID", models.AutoField(primary_key=True, serialize=False)),
                ("SkillDescription", models.TextField(blank=True, null=True)),
                (
                    "Certifications",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("AvailableFrom", models.TimeField(blank=True, null=True)),
                ("AvailableTo", models.TimeField(blank=True, null=True)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Busy", "Busy"),
                            ("Inactive", "Inactive"),
                        ],
                        default="Available",
                        max_length=50,
                    ),
                ),
                ("Rating", models.FloatField(default=0)),
                ("NumberOfRatings", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                ("ServiceID", models.AutoField(primary_key=True, serialize=False)),
                ("ServiceName", models.CharField(max_length=255)),
                ("Description", models.TextField(blank=True, null=True)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Duration", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("UserID", models.AutoField(primary_key=True, serialize=False)),
                ("FullName", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Phone", models.CharField(max_length=20, unique=True)),
                ("PasswordHash", models.CharField(max_length=255)),
                (
                    "Role",
                    models.CharField(
                        choices=[
                            ("Customer", "Customer"),
                            ("Provider", "Provider"),
                            ("Admin", "Admin"),
                        ],
                        max_length=50,
                    ),
                ),
                ("Address", models.CharField(blank=True, max_length=255, null=True)),
                ("Verified", models.BooleanField(default=False)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("PaymentID", models.AutoField(primary_key=True, serialize=False)),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "PaymentMethod",
                    models.CharField(
                        choices=[("Bank Transfer", "Bank Transfer"), ("Cash", "Cash")],
                        max_length=50,
                    ),
                ),
                ("PaymentDate", models.DateTimeField(auto_now_add=True)),
                (
                    "PaymentStatus",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "AppointmentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.appointments",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointments",
            name="ProviderID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.providers"
            ),
        ),
        migrations.CreateModel(
            name="ProviderServices",
            fields=[
                (
                    "ProviderServiceID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "ProviderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.providers",
                    ),
                ),
                (
                    "ServiceID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.services"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointments",
            name="ServiceID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.services"
            ),
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                ("ReviewID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("Comment", models.TextField(blank=True, null=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "ProviderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.providers",
                    ),
                ),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.users"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="providers",
            name="UserID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.users"
            ),
        ),
        migrations.CreateModel(
            name="Blogs",
            fields=[
                ("BlogID", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=255)),
                ("Content", models.TextField()),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                (
                    "AuthorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.users"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointments",
            name="CustomerID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.users"
            ),
        ),
    ]
