# Generated by Django 5.0.3 on 2024-10-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
